# Generated by Django 5.2.1 on 2025-06-11 11:33

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import quantityfield.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("researcher", "Researcher"),
                            ("admin", "Administrator"),
                        ],
                        default="user",
                        help_text="User role that determines access permissions",
                        max_length=20,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                (
                    "institution",
                    models.CharField(
                        blank=True,
                        help_text="University, company, or research institution",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "auth_user",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="PredictionInput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stoichiometric_imbalance", models.FloatField()),
                ("crosslink_conversion", models.FloatField()),
                ("crosslink_functionality", models.IntegerField()),
                (
                    "extract_solvent_before_measurement",
                    models.BooleanField(default=False),
                ),
                ("disable_primary_loops", models.BooleanField(default=False)),
                ("disable_secondary_loops", models.BooleanField(default=False)),
                ("functionalize_discrete", models.BooleanField(default=False)),
                ("n_zerofunctional_chains", models.IntegerField()),
                ("n_monofunctional_chains", models.IntegerField()),
                ("n_bifunctional_chains", models.IntegerField()),
                ("n_beads_zerofunctional", models.IntegerField()),
                ("n_beads_monofunctional", models.IntegerField()),
                ("n_beads_bifunctional", models.IntegerField()),
                ("n_beads_xlink", models.IntegerField(default=1)),
                (
                    "temperature",
                    quantityfield.fields.QuantityField(
                        base_units="K", unit_choices=["K"]
                    ),
                ),
                (
                    "density",
                    quantityfield.fields.QuantityField(
                        base_units="kg/cm^3", unit_choices=["kg/cm^3"]
                    ),
                ),
                (
                    "bead_mass",
                    quantityfield.fields.QuantityField(
                        base_units="kg/mol", unit_choices=["kg/mol"]
                    ),
                ),
                (
                    "mean_squared_bead_distance",
                    quantityfield.fields.QuantityField(
                        base_units="nm^2", unit_choices=["nm^2"]
                    ),
                ),
                (
                    "plateau_modulus",
                    quantityfield.fields.QuantityField(
                        base_units="MPa", unit_choices=["MPa"]
                    ),
                ),
                (
                    "entanglement_sampling_cutoff",
                    quantityfield.fields.QuantityField(
                        base_units="nm", unit_choices=["nm"]
                    ),
                ),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField(blank=True)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this prediction",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
