# Generated by Django 5.2.1 on 2025-06-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pylimerpredictor", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="predictioninput",
            old_name="n_beads_xlink",
            new_name="n_beads_xlinks",
        ),
        migrations.AddField(
            model_name="predictioninput",
            name="polymer_name",
            field=models.TextField(
                blank=True,
                help_text="Name of the polymer for which the prediction is made",
            ),
        ),
    ]
